== Enterprise Coffee

This is the coffee shop example project for the hands-on-lab: _Build Your Microservices workshop_

It comprises two applications, _coffee-shop_ and _barista_, built by Java EE and MicroProfile, which are deployed to a Kubernetes and Istio cluster.

Please use the following steps prior to the lab:

1. Register in IBM cloud (https://cloud.ibm.com/registration)

2. Convert your account to Trial by requesting coupon at https://ibm.biz/cloudcoupon and applying coupon to your Lite Account

3. Request your free IKS cluster in IBM Cloud (instructions are link:workshop/00-prerequisites.adoc[here])

4. Request credentials to VM with all IBM Cloud tools, maven and java installed: https://workshop-resources.eu-de.mybluemix.net?wi=istio202109

The contents of the workshop starts with the link:workshop/00-prerequisites.adoc[prerequisites].

=== Finish

After you've finished the walk-through you can compare your result with the https://github.com/agavrin/cloud-native-workshop-2021/tree/finish[finished version^].
